"""first

Revision ID: a2c902c03631
Revises: 
Create Date: 2020-05-10 18:55:49.308771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c902c03631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=128), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('payout_rules', sa.String(length=128), nullable=True),
    sa.Column('entry_code', sa.String(length=128), nullable=True),
    sa.Column('entrants', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fpl_id', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fpl_gameweek',
    sa.Column('fpl_gameweek_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fpl_event', sa.Integer(), nullable=True),
    sa.Column('fpl_points', sa.Integer(), nullable=True),
    sa.Column('chip', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fpl_gameweek_id')
    )
    op.create_index(op.f('ix_fpl_gameweek_user_id'), 'fpl_gameweek', ['user_id'], unique=False)
    op.create_table('gameweek_performance',
    sa.Column('gwpf_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=128), nullable=True),
    sa.Column('fpl_event', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['player.element_id'], ),
    sa.PrimaryKeyConstraint('gwpf_id', 'element_id')
    )
    op.create_table('gameweek_pick',
    sa.Column('gameweeks_pick_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('fpl_event', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('is_captain', sa.Integer(), nullable=True),
    sa.Column('is_vice_captain', sa.Integer(), nullable=True),
    sa.Column('auto_sub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['player.element_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('gameweeks_pick_id')
    )
    op.create_index(op.f('ix_gameweek_pick_user_id'), 'gameweek_pick', ['user_id'], unique=False)
    op.create_table('league_gameweek',
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_event', sa.Integer(), nullable=True),
    sa.Column('fpl_points', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('championship_points', sa.Integer(), nullable=True),
    sa.Column('fines', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('gameweek_id', 'id', 'league_id')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('id', 'league_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_table('league_gameweek')
    op.drop_index(op.f('ix_gameweek_pick_user_id'), table_name='gameweek_pick')
    op.drop_table('gameweek_pick')
    op.drop_table('gameweek_performance')
    op.drop_index(op.f('ix_fpl_gameweek_user_id'), table_name='fpl_gameweek')
    op.drop_table('fpl_gameweek')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('league')
    # ### end Alembic commands ###
