"""month column

Revision ID: e89e9d986f92
Revises: a2c902c03631
Create Date: 2020-05-11 19:35:39.427527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89e9d986f92'
down_revision = 'a2c902c03631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.alter_column('gameweek_performance', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('league_gameweek', sa.Column('month', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_gameweek', 'month')
    op.alter_column('gameweek_performance', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
